# -*- coding: utf-8 -*-
"""BTVN_AI_Tuan 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NVmo0ZNUTx_Il4j9qb9EPfG5cFHXgpa
"""

#23.1
!pip install folium

import folium
from folium.plugins import Fullscreen
from IPython.display import display

lat, lon = 10.7769, 106.6953  # UEH

ban_do = folium.Map(location=[lat, lon], zoom_start=15)

lop_trungtam = folium.FeatureGroup(name="Trung tâm")
lop_diem = folium.FeatureGroup(name="Địa điểm xung quanh")

folium.Marker(
    [lat, lon],
    popup="UEH - Cơ sở A",
    icon=folium.Icon(color="red")
).add_to(lop_trungtam)

ds = [
    [10.7740,106.6935,"BV Từ Dũ"],
    [10.7802,106.6981,"BV Bình Dân"],
    [10.7765,106.7000,"Vincom"],
    [10.7768,106.7010,"UBND Q1"],
    [10.7790,106.7005,"Trạm xe buýt"]
]

for d in ds:
    folium.Marker(
        [d[0], d[1]],
        popup=d[2],
        icon=folium.Icon(color="blue")
    ).add_to(lop_diem)

lop_trungtam.add_to(ban_do)
lop_diem.add_to(ban_do)

Fullscreen().add_to(ban_do)
folium.LayerControl().add_to(ban_do)

display(ban_do)

#23.2
!pip install folium geopy pandas

import time
import pandas as pd
import folium
from folium.plugins import Fullscreen
from geopy.geocoders import Nominatim
from geopy.distance import geodesic
from IPython.display import display

geolocator = Nominatim(user_agent="bai_tap_23_2")

ten_trung_tam = "UEH - Cơ sở A"
dia_chi_trung_tam = "59C Nguyen Dinh Chieu, District 3, Ho Chi Minh City, Vietnam"

du_phong_trung_tam = (10.7769, 106.6953)

ds_dia_diem = [
    {"ten": "Bệnh viện Từ Dũ", "dia_chi": "284 Cong Quynh, District 1, Ho Chi Minh City, Vietnam", "du_phong": (10.7678, 106.6878)},
    {"ten": "Bệnh viện Bình Dân", "dia_chi": "371 Dien Bien Phu, District 3, Ho Chi Minh City, Vietnam", "du_phong": (10.7726, 106.6819)},
    {"ten": "Dinh Độc Lập", "dia_chi": "135 Nam Ky Khoi Nghia, District 1, Ho Chi Minh City, Vietnam", "du_phong": (10.7771, 106.6953)},
    {"ten": "Nhà thờ Đức Bà", "dia_chi": "01 Cong xa Paris, District 1, Ho Chi Minh City, Vietnam", "du_phong": (10.7798, 106.6990)},
    {"ten": "Bưu điện Thành phố", "dia_chi": "02 Cong xa Paris, District 1, Ho Chi Minh City, Vietnam", "du_phong": (10.7801, 106.6993)},
    {"ten": "Chợ Bến Thành", "dia_chi": "Le Loi, District 1, Ho Chi Minh City, Vietnam", "du_phong": (10.7725, 106.6980)},
    {"ten": "Vincom Đồng Khởi", "dia_chi": "72 Le Thanh Ton, District 1, Ho Chi Minh City, Vietnam", "du_phong": (10.7793, 106.7035)},
    {"ten": "Tao Đàn Park", "dia_chi": "Truong Dinh, District 1, Ho Chi Minh City, Vietnam", "du_phong": (10.7754, 106.6919)},
    {"ten": "Nhà văn hóa Thanh Niên", "dia_chi": "4 Pham Ngoc Thach, District 1, Ho Chi Minh City, Vietnam", "du_phong": (10.7817, 106.6948)},
    {"ten": "Hồ Con Rùa", "dia_chi": "Cong truong Quoc te, District 3, Ho Chi Minh City, Vietnam", "du_phong": (10.7840, 106.6933)}
]

def lay_toa_do(dia_chi, toa_do_du_phong):
    try:
        vi_tri = geolocator.geocode(dia_chi, timeout=10)
        time.sleep(1)
        if vi_tri:
            return (vi_tri.latitude, vi_tri.longitude)
        return toa_do_du_phong
    except:
        return toa_do_du_phong

toa_do_trung_tam = lay_toa_do(dia_chi_trung_tam, du_phong_trung_tam)

ket_qua = []

for diem in ds_dia_diem:
    toa_do = lay_toa_do(diem["dia_chi"], diem["du_phong"])
    khoang_cach = geodesic(toa_do_trung_tam, toa_do).km

    ket_qua.append({
        "Tên địa điểm": diem["ten"],
        "Địa chỉ": diem["dia_chi"],
        "Vĩ độ": round(toa_do[0], 6),
        "Kinh độ": round(toa_do[1], 6),
        "Khoảng cách đến trung tâm (km)": round(khoang_cach, 2)
    })

bang = pd.DataFrame(ket_qua)
display(bang)

ban_do = folium.Map(location=toa_do_trung_tam, zoom_start=14)

lop_trung_tam = folium.FeatureGroup(name="Điểm trung tâm")
lop_dia_diem = folium.FeatureGroup(name="Các địa điểm")
lop_duong_noi = folium.FeatureGroup(name="Mối quan hệ không gian")

folium.Marker(
    toa_do_trung_tam,
    popup=f"<b>{ten_trung_tam}</b><br>{dia_chi_trung_tam}",
    tooltip=ten_trung_tam,
    icon=folium.Icon(color="red")
).add_to(lop_trung_tam)

for i in range(len(bang)):
    lat = bang.loc[i, "Vĩ độ"]
    lon = bang.loc[i, "Kinh độ"]
    ten = bang.loc[i, "Tên địa điểm"]
    dia_chi = bang.loc[i, "Địa chỉ"]
    kc = bang.loc[i, "Khoảng cách đến trung tâm (km)"]

    folium.Marker(
        [lat, lon],
        popup=f"<b>{ten}</b><br>{dia_chi}<br>Khoảng cách đến {ten_trung_tam}: {kc} km",
        tooltip=ten,
        icon=folium.Icon(color="blue")
    ).add_to(lop_dia_diem)

    folium.PolyLine(
        locations=[toa_do_trung_tam, [lat, lon]],
        tooltip=f"{ten}: {kc} km",
        color="green",
        weight=2
    ).add_to(lop_duong_noi)

lop_trung_tam.add_to(ban_do)
lop_dia_diem.add_to(ban_do)
lop_duong_noi.add_to(ban_do)

Fullscreen().add_to(ban_do)
folium.LayerControl().add_to(ban_do)

display(ban_do)

#23.3
!pip install folium

import folium
from folium.plugins import HeatMap, Fullscreen
from IPython.display import display

lat_trung_tam = 10.7769
lon_trung_tam = 106.6953

ban_do = folium.Map(location=[lat_trung_tam, lon_trung_tam], zoom_start=14)

folium.Marker(
    [lat_trung_tam, lon_trung_tam],
    popup="Trung tâm phân tích",
    tooltip="Trung tâm",
    icon=folium.Icon(color="red")
).add_to(ban_do)

du_lieu_nhiet = [
    [10.7768, 106.6951, 8],
    [10.7769, 106.6953, 9],
    [10.7770, 106.6955, 10],
    [10.7771, 106.6957, 9],
    [10.7767, 106.6954, 8],
    [10.7766, 106.6950, 7],
    [10.7772, 106.6952, 9],
    [10.7773, 106.6958, 10],
    [10.7765, 106.6948, 7],
    [10.7774, 106.6960, 8],

    [10.7805, 106.6995, 6],
    [10.7807, 106.6997, 7],
    [10.7809, 106.7000, 6],
    [10.7810, 106.7002, 5],
    [10.7806, 106.7001, 6],

    [10.7730, 106.6905, 3],
    [10.7732, 106.6908, 2],
    [10.7734, 106.6910, 3],
    [10.7736, 106.6912, 2],

    [10.7845, 106.7035, 1],
    [10.7848, 106.7038, 1],
    [10.7850, 106.7040, 1]
]

HeatMap(
    du_lieu_nhiet,
    radius=25,
    blur=18,
    max_zoom=17
).add_to(ban_do)

lop_diem = folium.FeatureGroup(name="Các điểm giả lập")

for diem in du_lieu_nhiet:
    folium.CircleMarker(
        location=[diem[0], diem[1]],
        radius=4,
        popup=f"Tọa độ: ({diem[0]}, {diem[1]})<br>Mức độ: {diem[2]}",
        fill=True
    ).add_to(lop_diem)

lop_diem.add_to(ban_do)

Fullscreen().add_to(ban_do)
folium.LayerControl().add_to(ban_do)

display(ban_do)

print("Nhận xét:")
print("- Vùng đỏ, cam là khu vực có mật độ cao, tập trung nhiều khách hàng hoặc đơn hàng.")
print("- Vùng xanh, nhạt là khu vực có mật độ thấp, mức độ phát sinh ít hơn.")
print("- Ý nghĩa quản trị: doanh nghiệp có thể ưu tiên mở rộng dịch vụ, bố trí nhân sự, quảng cáo hoặc điểm giao dịch tại vùng nóng.")
print("- Với vùng mật độ thấp, doanh nghiệp có thể xem xét tối ưu chi phí hoặc triển khai chương trình thu hút thêm khách hàng.")

#23.4
!pip install folium geopandas pandas

import folium
import json
import pandas as pd
from IPython.display import display

geojson_data = {
    "type": "FeatureCollection",
    "features": [
        {"type":"Feature","properties":{"khu_vuc":"A"},"geometry":{"type":"Polygon","coordinates":[[[106.69,10.77],[106.695,10.77],[106.695,10.775],[106.69,10.775],[106.69,10.77]]]}},
        {"type":"Feature","properties":{"khu_vuc":"B"},"geometry":{"type":"Polygon","coordinates":[[[106.695,10.77],[106.70,10.77],[106.70,10.775],[106.695,10.775],[106.695,10.77]]]}},
        {"type":"Feature","properties":{"khu_vuc":"C"},"geometry":{"type":"Polygon","coordinates":[[[106.70,10.77],[106.705,10.77],[106.705,10.775],[106.70,10.775],[106.70,10.77]]]}},
        {"type":"Feature","properties":{"khu_vuc":"D"},"geometry":{"type":"Polygon","coordinates":[[[106.69,10.775],[106.695,10.775],[106.695,10.78],[106.69,10.78],[106.69,10.775]]]}},
        {"type":"Feature","properties":{"khu_vuc":"E"},"geometry":{"type":"Polygon","coordinates":[[[106.695,10.775],[106.70,10.775],[106.70,10.78],[106.695,10.78],[106.695,10.775]]]}},
        {"type":"Feature","properties":{"khu_vuc":"F"},"geometry":{"type":"Polygon","coordinates":[[[106.70,10.775],[106.705,10.775],[106.705,10.78],[106.70,10.78],[106.70,10.775]]]}}
    ]
}

with open("map.geojson","w") as f:
    json.dump(geojson_data,f)

data = pd.DataFrame({
    "khu_vuc":["A","B","C","D","E","F"],
    "gia_tri":[120,250,180,90,300,160]
})

ban_do = folium.Map(location=[10.7769,106.6953], zoom_start=14)

folium.Choropleth(
    geo_data="map.geojson",
    data=data,
    columns=["khu_vuc","gia_tri"],
    key_on="feature.properties.khu_vuc",
    fill_color="YlOrRd",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Số đơn hàng"
).add_to(ban_do)

folium.LayerControl().add_to(ban_do)

display(ban_do)

print("Nhận xét:")
print("- Màu càng đậm → giá trị càng cao")
print("- Khu vực E và B có mức cao → nên tập trung nguồn lực")
print("- Khu vực D thấp → cần cải thiện hoặc kích cầu")

#23.5
!pip install folium geopy

import folium
from geopy.distance import geodesic
from IPython.display import display

trung_tam = (10.7769, 106.6953)

khach_hang = [
    (10.7820, 106.6980, "KH1"),
    (10.7805, 106.6905, "KH2"),
    (10.7735, 106.7000, "KH3"),
    (10.7700, 106.6925, "KH4"),
    (10.7685, 106.7005, "KH5"),
    (10.7850, 106.7050, "KH6"),
    (10.7900, 106.7100, "KH7"),
    (10.7650, 106.6850, "KH8"),
    (10.7580, 106.6780, "KH9"),
    (10.8000, 106.7200, "KH10"),
    (10.7720, 106.6880, "KH11"),
    (10.7815, 106.7010, "KH12")
]

ban_do = folium.Map(location=trung_tam, zoom_start=13)

folium.Marker(
    trung_tam,
    popup="Trung tâm phân phối",
    tooltip="Trung tâm",
    icon=folium.Icon(color="red")
).add_to(ban_do)

folium.Circle(
    location=trung_tam,
    radius=3000,
    color="green",
    fill=True,
    fill_opacity=0.15,
    popup="Vùng phục vụ 3 km"
).add_to(ban_do)

folium.Circle(
    location=trung_tam,
    radius=5000,
    color="blue",
    fill=True,
    fill_opacity=0.1,
    popup="Vùng phục vụ 5 km"
).add_to(ban_do)

folium.Circle(
    location=trung_tam,
    radius=10000,
    color="purple",
    fill=True,
    fill_opacity=0.08,
    popup="Vùng phục vụ 10 km"
).add_to(ban_do)

dem_3 = 0
dem_5 = 0
dem_10 = 0

for lat, lon, ten in khach_hang:
    kc = geodesic(trung_tam, (lat, lon)).km

    if kc <= 3:
        mau = "green"
        vung = "Trong 3 km"
        dem_3 += 1
        dem_5 += 1
        dem_10 += 1
    elif kc <= 5:
        mau = "blue"
        vung = "Trong 5 km"
        dem_5 += 1
        dem_10 += 1
    elif kc <= 10:
        mau = "purple"
        vung = "Trong 10 km"
        dem_10 += 1
    else:
        mau = "gray"
        vung = "Ngoài 10 km"

    folium.Marker(
        [lat, lon],
        popup=f"{ten}<br>Khoảng cách: {kc:.2f} km<br>{vung}",
        tooltip=ten,
        icon=folium.Icon(color=mau)
    ).add_to(ban_do)

display(ban_do)

tong = len(khach_hang)

print("KẾT QUẢ PHÂN TÍCH")
print("Số khách hàng trong 3 km:", dem_3)
print("Số khách hàng trong 5 km:", dem_5)
print("Số khách hàng trong 10 km:", dem_10)
print("Tổng số khách hàng:", tong)

print()
print("NHẬN XÉT")
print("- Vùng 3 km phục vụ nhóm khách hàng gần nhất, thời gian giao hàng nhanh, chi phí thấp.")
print("- Vùng 5 km mở rộng thêm phạm vi tiếp cận và vẫn tương đối thuận lợi cho vận hành.")
print("- Vùng 10 km bao phủ nhiều khách hàng hơn nhưng chi phí và thời gian phục vụ sẽ cao hơn.")
print("- Nếu mục tiêu là cân bằng giữa độ phủ và hiệu quả vận hành thì vùng 5 km là phạm vi hoạt động tối ưu.")

#23.6
!pip install osmnx

import osmnx as ox
import matplotlib.pyplot as plt

ox.settings.use_cache = True
ox.settings.log_console = False

dia_diem = "District 1, Ho Chi Minh City, Vietnam"

G = ox.graph_from_place(dia_diem, network_type="drive")

fig, ax = ox.plot_graph(
    G,
    node_size=5,
    edge_linewidth=0.5,
    show=False,
    close=False
)
plt.show()

so_nut = len(G.nodes)
so_canh = len(G.edges)

tong_chieu_dai = sum(data["length"] for u, v, data in G.edges(data=True))
chieu_dai_tb = tong_chieu_dai / so_canh

print("KẾT QUẢ PHÂN TÍCH")
print("Số nút giao:", so_nut)
print("Số đoạn đường:", so_canh)
print("Chiều dài trung bình (m):", round(chieu_dai_tb, 2))

print()
print("Nhận xét:")
print("- Mạng đường thể hiện cấu trúc giao thông của khu vực nghiên cứu.")
print("- Số nút giao phản ánh mức độ kết nối giữa các tuyến đường.")
print("- Chiều dài đường trung bình giúp mô tả đặc điểm phân bố mạng lưới.")
print("- Dữ liệu mạng giao thông rất quan trọng trong AI đô thị thông minh, ví dụ như tìm đường, dự báo ùn tắc và tối ưu vận chuyển.")

#23.7
!pip install osmnx folium

import osmnx as ox
import networkx as nx
import folium
from IPython.display import display

ox.settings.use_cache = True
ox.settings.log_console = False

place = "District 1, Ho Chi Minh City, Vietnam"

G = ox.graph_from_place(place, network_type="drive")

diem_A = (10.7769, 106.6953)
diem_B = (10.7700, 106.7000)

node_A = ox.distance.nearest_nodes(G, diem_A[1], diem_A[0])
node_B = ox.distance.nearest_nodes(G, diem_B[1], diem_B[0])

route_dijkstra = nx.shortest_path(G, node_A, node_B, weight="length")

def heuristic(u, v):
    y1, x1 = G.nodes[u]["y"], G.nodes[u]["x"]
    y2, x2 = G.nodes[v]["y"], G.nodes[v]["x"]
    return ((y1 - y2)**2 + (x1 - x2)**2)**0.5

route_astar = nx.astar_path(G, node_A, node_B, heuristic=heuristic, weight="length")

def get_length(graph, route):
    tong = 0
    for u, v in zip(route[:-1], route[1:]):
        data = graph.get_edge_data(u, v)
        if data is not None:
            canh_ngan_nhat = min(data.values(), key=lambda x: x["length"])
            tong += canh_ngan_nhat["length"]
    return tong

len_dijkstra = get_length(G, route_dijkstra)
len_astar = get_length(G, route_astar)

print("Chiều dài Dijkstra (m):", round(len_dijkstra, 2))
print("Chiều dài A* (m):", round(len_astar, 2))

m = folium.Map(location=diem_A, zoom_start=14)

coords_dijkstra = [(G.nodes[n]["y"], G.nodes[n]["x"]) for n in route_dijkstra]
coords_astar = [(G.nodes[n]["y"], G.nodes[n]["x"]) for n in route_astar]

folium.PolyLine(
    coords_dijkstra,
    color="blue",
    weight=5,
    tooltip="Dijkstra"
).add_to(m)

folium.PolyLine(
    coords_astar,
    color="red",
    weight=3,
    tooltip="A*"
).add_to(m)

folium.Marker(
    diem_A,
    popup="Điểm A",
    icon=folium.Icon(color="green")
).add_to(m)

folium.Marker(
    diem_B,
    popup="Điểm B",
    icon=folium.Icon(color="red")
).add_to(m)

display(m)

print()
print("NHẬN XÉT")
print("- Dijkstra tìm đường đi ngắn nhất chính xác nhưng thường duyệt nhiều nút hơn.")
print("- A* dùng heuristic nên thường tìm nhanh hơn.")
print("- Nếu heuristic phù hợp thì kết quả A* và Dijkstra thường rất gần nhau hoặc giống nhau.")
print("- Trong giao thông thông minh, A* phù hợp cho tìm đường thời gian thực.")

#23.8
!pip install folium geopy

import folium
from geopy.distance import geodesic
from IPython.display import display

xe = [
    {"ten": "Xe 1", "toa_do": (10.7765, 106.6948)},
    {"ten": "Xe 2", "toa_do": (10.7790, 106.6985)},
    {"ten": "Xe 3", "toa_do": (10.7735, 106.6915)},
    {"ten": "Xe 4", "toa_do": (10.7810, 106.7020)},
    {"ten": "Xe 5", "toa_do": (10.7705, 106.6960)}
]

khach = [
    {"ten": "Khách 1", "toa_do": (10.7778, 106.6955)},
    {"ten": "Khách 2", "toa_do": (10.7802, 106.7005)},
    {"ten": "Khách 3", "toa_do": (10.7728, 106.6928)},
    {"ten": "Khách 4", "toa_do": (10.7698, 106.6972)}
]

xe_con_trong = xe.copy()
ket_qua_ghep = []

for k in khach:
    xe_gan_nhat = None
    kc_nho_nhat = 10**9

    for x in xe_con_trong:
        kc = geodesic(k["toa_do"], x["toa_do"]).km
        if kc < kc_nho_nhat:
            kc_nho_nhat = kc
            xe_gan_nhat = x

    ket_qua_ghep.append({
        "khach": k["ten"],
        "xe": xe_gan_nhat["ten"],
        "toa_do_khach": k["toa_do"],
        "toa_do_xe": xe_gan_nhat["toa_do"],
        "khoang_cach": kc_nho_nhat
    })

    xe_con_trong.remove(xe_gan_nhat)

ban_do = folium.Map(location=[10.7769, 106.6953], zoom_start=14)

lop_xe = folium.FeatureGroup(name="Vị trí xe")
lop_khach = folium.FeatureGroup(name="Vị trí khách")
lop_ghep = folium.FeatureGroup(name="Ghép xe - khách")

for x in xe:
    folium.Marker(
        x["toa_do"],
        popup=x["ten"],
        tooltip=x["ten"],
        icon=folium.Icon(color="blue", icon="car", prefix="fa")
    ).add_to(lop_xe)

for k in khach:
    folium.Marker(
        k["toa_do"],
        popup=k["ten"],
        tooltip=k["ten"],
        icon=folium.Icon(color="red", icon="user", prefix="fa")
    ).add_to(lop_khach)

for g in ket_qua_ghep:
    folium.PolyLine(
        locations=[g["toa_do_xe"], g["toa_do_khach"]],
        color="green",
        weight=3,
        tooltip=f'{g["xe"]} -> {g["khach"]}'
    ).add_to(lop_ghep)

    folium.Marker(
        g["toa_do_khach"],
        popup=f'{g["khach"]}<br>Được ghép với {g["xe"]}<br>Khoảng cách: {g["khoang_cach"]:.2f} km',
        icon=folium.Icon(color="red", icon="user", prefix="fa")
    ).add_to(lop_ghep)

lop_xe.add_to(ban_do)
lop_khach.add_to(ban_do)
lop_ghep.add_to(ban_do)

folium.LayerControl().add_to(ban_do)

display(ban_do)

print("KẾT QUẢ GHÉP XE")
for g in ket_qua_ghep:
    print(f'{g["khach"]} <- {g["xe"]} | Khoảng cách: {g["khoang_cach"]:.2f} km')

print()
print("NHẬN XÉT")
print("- Bài toán sử dụng heuristic gần nhất để gán xe cho từng khách hàng.")
print("- Mỗi khách được ghép với xe đang rảnh có khoảng cách ngắn nhất.")
print("- Cách này giúp giảm thời gian chờ và quãng đường đón khách.")
print("- Trong thực tế, hệ thống có thể mở rộng thêm tiêu chí như thời gian di chuyển, mật độ giao thông hoặc mức giá.")

#23.9
!pip install folium scikit-learn

import folium
import numpy as np
from sklearn.cluster import KMeans
from IPython.display import display

khach_hang = np.array([
    [10.7765,106.6950],
    [10.7770,106.6960],
    [10.7780,106.6970],
    [10.7800,106.7000],
    [10.7810,106.7010],
    [10.7820,106.7020],

    [10.7720,106.6900],
    [10.7710,106.6890],
    [10.7700,106.6880],

    [10.7850,106.7050],
    [10.7860,106.7060],
    [10.7870,106.7070]
])

k = 3
model = KMeans(n_clusters=k, random_state=0)
labels = model.fit_predict(khach_hang)

centers = model.cluster_centers_

ban_do = folium.Map(location=[10.7769,106.6953], zoom_start=14)

colors = ["red","blue","green"]

for i in range(len(khach_hang)):
    folium.CircleMarker(
        location=khach_hang[i],
        radius=5,
        color=colors[labels[i]],
        fill=True,
        fill_opacity=0.7,
        popup=f"Cluster {labels[i]}"
    ).add_to(ban_do)

for i, c in enumerate(centers):
    folium.Marker(
        location=c,
        popup=f"Trạm đề xuất {i}",
        icon=folium.Icon(color="black", icon="home")
    ).add_to(ban_do)

display(ban_do)

print("Tọa độ các trạm đề xuất:")
for i, c in enumerate(centers):
    print(f"Trạm {i}: ({c[0]:.4f}, {c[1]:.4f})")

print()
print("NHẬN XÉT")
print("- Dữ liệu khách hàng được chia thành 3 cụm dựa trên vị trí địa lý.")
print("- Tâm cụm đại diện cho vị trí tối ưu để đặt trạm hoặc kho.")
print("- Việc đặt trạm gần trung tâm cụm giúp giảm chi phí vận chuyển và thời gian phục vụ.")
print("- Đây là cách ứng dụng học máy vào bài toán tối ưu hóa logistics và phân phối.")

#23.10
!pip install folium pandas

import folium
import pandas as pd
from IPython.display import display

du_lieu = pd.DataFrame([
    {"ten":"Đoạn 1", "lat":10.7760, "lon":106.6950, "mat_do":90, "toc_do":12, "su_co":2},
    {"ten":"Đoạn 2", "lat":10.7775, "lon":106.6970, "mat_do":80, "toc_do":15, "su_co":1},
    {"ten":"Đoạn 3", "lat":10.7790, "lon":106.6990, "mat_do":65, "toc_do":22, "su_co":1},
    {"ten":"Đoạn 4", "lat":10.7745, "lon":106.6930, "mat_do":40, "toc_do":35, "su_co":0},
    {"ten":"Đoạn 5", "lat":10.7725, "lon":106.6910, "mat_do":30, "toc_do":40, "su_co":0},
    {"ten":"Đoạn 6", "lat":10.7810, "lon":106.7010, "mat_do":85, "toc_do":10, "su_co":2},
    {"ten":"Đoạn 7", "lat":10.7830, "lon":106.7030, "mat_do":55, "toc_do":25, "su_co":0},
    {"ten":"Đoạn 8", "lat":10.7705, "lon":106.6895, "mat_do":35, "toc_do":38, "su_co":0}
])

def tinh_rui_ro(mat_do, toc_do, su_co):
    diem = 0.5 * mat_do + 0.3 * (60 - toc_do) + 10 * su_co
    return diem

def xep_loai(diem):
    if diem >= 70:
        return "Cao", "red"
    elif diem >= 45:
        return "Trung bình", "orange"
    else:
        return "Thấp", "green"

du_lieu["diem_rui_ro"] = du_lieu.apply(
    lambda x: tinh_rui_ro(x["mat_do"], x["toc_do"], x["su_co"]), axis=1
)

muc_do = du_lieu["diem_rui_ro"].apply(xep_loai)
du_lieu["muc_rui_ro"] = [x[0] for x in muc_do]
du_lieu["mau"] = [x[1] for x in muc_do]

ban_do = folium.Map(location=[10.7769, 106.6953], zoom_start=14)

lop_rui_ro = folium.FeatureGroup(name="Điểm rủi ro")
lop_tuyen = folium.FeatureGroup(name="Tuyến thay thế")

for i in range(len(du_lieu)):
    row = du_lieu.loc[i]
    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=10,
        color=row["mau"],
        fill=True,
        fill_opacity=0.7,
        popup=(
            f'<b>{row["ten"]}</b><br>'
            f'Mật độ xe: {row["mat_do"]}<br>'
            f'Tốc độ TB: {row["toc_do"]} km/h<br>'
            f'Sự cố: {row["su_co"]}<br>'
            f'Điểm rủi ro: {row["diem_rui_ro"]:.1f}<br>'
            f'Mức nguy cơ: {row["muc_rui_ro"]}'
        ),
        tooltip=f'{row["ten"]} - {row["muc_rui_ro"]}'
    ).add_to(lop_rui_ro)

tuyen_chinh = [
    [10.7760, 106.6950],
    [10.7775, 106.6970],
    [10.7790, 106.6990],
    [10.7810, 106.7010]
]

tuyen_thay_the = [
    [10.7760, 106.6950],
    [10.7745, 106.6930],
    [10.7725, 106.6910],
    [10.7705, 106.6895]
]

folium.PolyLine(
    tuyen_chinh,
    color="red",
    weight=5,
    tooltip="Tuyến chính - nguy cơ tắc nghẽn cao",
    popup="Tuyến chính đi qua nhiều đoạn có rủi ro cao"
).add_to(lop_tuyen)

folium.PolyLine(
    tuyen_thay_the,
    color="blue",
    weight=5,
    tooltip="Tuyến thay thế",
    popup="Tuyến thay thế có mức rủi ro thấp hơn"
).add_to(lop_tuyen)

folium.Marker(
    tuyen_chinh[0],
    popup="Điểm bắt đầu",
    icon=folium.Icon(color="green")
).add_to(lop_tuyen)

folium.Marker(
    tuyen_chinh[-1],
    popup="Điểm kết thúc",
    icon=folium.Icon(color="black")
).add_to(lop_tuyen)

lop_rui_ro.add_to(ban_do)
lop_tuyen.add_to(ban_do)

folium.LayerControl().add_to(ban_do)

display(ban_do)

print("BẢNG KẾT QUẢ")
print(du_lieu[["ten", "mat_do", "toc_do", "su_co", "diem_rui_ro", "muc_rui_ro"]])

print()
print("NHẬN XÉT")
print("- Các đoạn màu đỏ là khu vực có nguy cơ tắc nghẽn cao do mật độ xe lớn, tốc độ thấp và có sự cố giao thông.")
print("- Các đoạn màu cam có nguy cơ trung bình, cần theo dõi thêm vào giờ cao điểm.")
print("- Các đoạn màu xanh có nguy cơ thấp, phù hợp để đề xuất làm tuyến thay thế.")
print("- Tuyến màu xanh dương được chọn vì đi qua các khu vực có mức rủi ro thấp hơn tuyến chính.")
print("- Về ý nghĩa quản trị, mô hình này hỗ trợ điều phối giao thông, cảnh báo sớm và đề xuất lộ trình phù hợp cho người dùng.")

#23.11
!pip install pandas scikit-learn folium

import pandas as pd
import folium
from sklearn.linear_model import LinearRegression
from IPython.display import display

du_lieu = pd.DataFrame([
    ["Khu vực A", 10.7765, 106.6950, 7, 35],
    ["Khu vực A", 10.7765, 106.6950, 9, 50],
    ["Khu vực A", 10.7765, 106.6950, 12, 60],
    ["Khu vực A", 10.7765, 106.6950, 18, 95],
    ["Khu vực A", 10.7765, 106.6950, 20, 80],

    ["Khu vực B", 10.7805, 106.6995, 7, 25],
    ["Khu vực B", 10.7805, 106.6995, 9, 40],
    ["Khu vực B", 10.7805, 106.6995, 12, 55],
    ["Khu vực B", 10.7805, 106.6995, 18, 85],
    ["Khu vực B", 10.7805, 106.6995, 20, 70],

    ["Khu vực C", 10.7725, 106.6910, 7, 20],
    ["Khu vực C", 10.7725, 106.6910, 9, 30],
    ["Khu vực C", 10.7725, 106.6910, 12, 42],
    ["Khu vực C", 10.7725, 106.6910, 18, 65],
    ["Khu vực C", 10.7725, 106.6910, 20, 50],

    ["Khu vực D", 10.7840, 106.7030, 7, 15],
    ["Khu vực D", 10.7840, 106.7030, 9, 28],
    ["Khu vực D", 10.7840, 106.7030, 12, 35],
    ["Khu vực D", 10.7840, 106.7030, 18, 55],
    ["Khu vực D", 10.7840, 106.7030, 20, 40]
], columns=["khu_vuc", "lat", "lon", "gio", "nhu_cau"])

ma_khu_vuc = {
    "Khu vực A": 0,
    "Khu vực B": 1,
    "Khu vực C": 2,
    "Khu vực D": 3
}

du_lieu["ma_khu"] = du_lieu["khu_vuc"].map(ma_khu_vuc)

X = du_lieu[["ma_khu", "gio"]]
y = du_lieu["nhu_cau"]

model = LinearRegression()
model.fit(X, y)

gio_du_doan = 19

du_doan = pd.DataFrame({
    "khu_vuc": ["Khu vực A", "Khu vực B", "Khu vực C", "Khu vực D"],
    "lat": [10.7765, 10.7805, 10.7725, 10.7840],
    "lon": [106.6950, 106.6995, 106.6910, 106.7030]
})

du_doan["ma_khu"] = du_doan["khu_vuc"].map(ma_khu_vuc)
du_doan["gio"] = gio_du_doan
du_doan["nhu_cau_du_doan"] = model.predict(du_doan[["ma_khu", "gio"]]).round(1)

def lay_mau(nhu_cau):
    if nhu_cau >= 80:
        return "red"
    elif nhu_cau >= 60:
        return "orange"
    else:
        return "green"

du_doan["mau"] = du_doan["nhu_cau_du_doan"].apply(lay_mau)

ban_do = folium.Map(location=[10.7769, 106.6953], zoom_start=14)

for i in range(len(du_doan)):
    row = du_doan.loc[i]
    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=row["nhu_cau_du_doan"] / 8,
        color=row["mau"],
        fill=True,
        fill_opacity=0.7,
        popup=(
            f'<b>{row["khu_vuc"]}</b><br>'
            f'Giờ dự đoán: {gio_du_doan}h<br>'
            f'Nhu cầu dự đoán: {row["nhu_cau_du_doan"]}'
        ),
        tooltip=f'{row["khu_vuc"]}: {row["nhu_cau_du_doan"]}'
    ).add_to(ban_do)

display(ban_do)

print("BẢNG DỰ ĐOÁN NHU CẦU")
print(du_doan[["khu_vuc", "gio", "nhu_cau_du_doan"]])

print()
print("NHẬN XÉT")
print("- Khu vực có vòng tròn lớn và màu nóng là nơi có nhu cầu dịch vụ cao hơn vào khung giờ dự đoán.")
print("- Khu vực A và B có xu hướng nhu cầu cao hơn, nên cần ưu tiên bố trí thêm xe hoặc nhân sự giao hàng.")
print("- Khu vực C và D có nhu cầu thấp hơn, có thể duy trì mức nguồn lực vừa phải.")
print("- Việc dự đoán nhu cầu theo khu vực và thời gian giúp doanh nghiệp điều phối nguồn lực hiệu quả hơn, giảm thời gian chờ và tăng chất lượng phục vụ.")

#23.12
!pip install folium geopy

import folium
import random
from geopy.distance import geodesic
from IPython.display import display

kho = [
    {"ten": "Kho 1", "toa_do": (10.7769, 106.6953)},
    {"ten": "Kho 2", "toa_do": (10.7820, 106.7000)}
]

don_hang = [
    (10.7800,106.6980),
    (10.7790,106.6940),
    (10.7750,106.6900),
    (10.7720,106.6920),
    (10.7710,106.6970),
    (10.7830,106.7030)
]

def tim_kho_gan_nhat(diem):
    return min(kho, key=lambda k: geodesic(diem, k["toa_do"]).km)

def tao_tuyen_toi_uu(start, points):
    chua_di = points.copy()
    hien_tai = start
    tuyen = [start]
    tong = 0

    while chua_di:
        diem_gan = min(chua_di, key=lambda p: geodesic(hien_tai, p).km)
        tong += geodesic(hien_tai, diem_gan).km
        hien_tai = diem_gan
        tuyen.append(diem_gan)
        chua_di.remove(diem_gan)

    return tuyen, tong

def tao_tuyen_ngau_nhien(start, points):
    ds = points.copy()
    random.shuffle(ds)
    tuyen = [start] + ds
    tong = 0

    for i in range(len(tuyen)-1):
        tong += geodesic(tuyen[i], tuyen[i+1]).km

    return tuyen, tong

ban_do = folium.Map(location=[10.7769,106.6953], zoom_start=14)

tong_opt = 0
tong_random = 0

for k in kho:
    diem_kho = k["toa_do"]
    ds_khach = [d for d in don_hang if tim_kho_gan_nhat(d) == k]

    if not ds_khach:
        continue

    tuyen_opt, kc_opt = tao_tuyen_toi_uu(diem_kho, ds_khach)
    tuyen_rand, kc_rand = tao_tuyen_ngau_nhien(diem_kho, ds_khach)

    tong_opt += kc_opt
    tong_random += kc_rand

    folium.PolyLine(tuyen_opt, color="green", weight=5, tooltip="Tối ưu").add_to(ban_do)
    folium.PolyLine(tuyen_rand, color="red", weight=3, tooltip="Ngẫu nhiên").add_to(ban_do)

    folium.Marker(diem_kho, popup=k["ten"], icon=folium.Icon(color="blue")).add_to(ban_do)

    for d in ds_khach:
        folium.CircleMarker(d, radius=5, color="black", fill=True).add_to(ban_do)

display(ban_do)

print("Tổng quãng đường (tối ưu):", round(tong_opt,2), "km")
print("Tổng quãng đường (ngẫu nhiên):", round(tong_random,2), "km")

print()
print("NHẬN XÉT")
print("- Tuyến tối ưu (màu xanh) sử dụng heuristic chọn điểm gần nhất nên giảm quãng đường di chuyển.")
print("- Tuyến ngẫu nhiên (màu đỏ) thường dài hơn do không có chiến lược lựa chọn.")
print("- Việc tối ưu tuyến giúp giảm chi phí vận chuyển và thời gian giao hàng.")
print("- Đây là ứng dụng của AI/heuristic trong bài toán logistics thực tế.")

#23.13
!pip install folium

import folium
from folium.plugins import Fullscreen, MiniMap, MeasureControl
from IPython.display import display

ban_do = folium.Map(location=[10.7769, 106.6953], zoom_start=14)

lop_diem = folium.FeatureGroup(name="Điểm dịch vụ")
lop_vung = folium.FeatureGroup(name="Vùng nhu cầu")
lop_tuyen = folium.FeatureGroup(name="Tuyến giao hàng")
lop_kho = folium.FeatureGroup(name="Kho trung tâm")

folium.Marker(
    [10.7769, 106.6953],
    popup="Kho trung tâm A",
    tooltip="Kho trung tâm A",
    icon=folium.Icon(color="red", icon="home")
).add_to(lop_kho)

folium.Marker(
    [10.7810, 106.7005],
    popup="Điểm giao 1<br>Nhu cầu: cao",
    tooltip="Điểm giao 1",
    icon=folium.Icon(color="blue")
).add_to(lop_diem)

folium.Marker(
    [10.7735, 106.6915],
    popup="Điểm giao 2<br>Nhu cầu: trung bình",
    tooltip="Điểm giao 2",
    icon=folium.Icon(color="blue")
).add_to(lop_diem)

folium.Marker(
    [10.7705, 106.6970],
    popup="Điểm giao 3<br>Nhu cầu: thấp",
    tooltip="Điểm giao 3",
    icon=folium.Icon(color="blue")
).add_to(lop_diem)

folium.Marker(
    [10.7840, 106.7030],
    popup="Điểm giao 4<br>Nhu cầu: cao",
    tooltip="Điểm giao 4",
    icon=folium.Icon(color="blue")
).add_to(lop_diem)

folium.Polygon(
    locations=[
        [10.7795, 106.6985],
        [10.7825, 106.6985],
        [10.7825, 106.7025],
        [10.7795, 106.7025]
    ],
    color="orange",
    fill=True,
    fill_opacity=0.35,
    popup="Vùng nhu cầu cao"
).add_to(lop_vung)

folium.Polygon(
    locations=[
        [10.7720, 106.6890],
        [10.7750, 106.6890],
        [10.7750, 106.6930],
        [10.7720, 106.6930]
    ],
    color="green",
    fill=True,
    fill_opacity=0.25,
    popup="Vùng nhu cầu trung bình"
).add_to(lop_vung)

folium.Polygon(
    locations=[
        [10.7685, 106.6955],
        [10.7715, 106.6955],
        [10.7715, 106.6995],
        [10.7685, 106.6995]
    ],
    color="purple",
    fill=True,
    fill_opacity=0.2,
    popup="Vùng nhu cầu thấp"
).add_to(lop_vung)

folium.PolyLine(
    locations=[
        [10.7769, 106.6953],
        [10.7810, 106.7005],
        [10.7840, 106.7030]
    ],
    color="red",
    weight=5,
    tooltip="Tuyến giao hàng 1",
    popup="Tuyến ưu tiên phục vụ vùng nhu cầu cao"
).add_to(lop_tuyen)

folium.PolyLine(
    locations=[
        [10.7769, 106.6953],
        [10.7735, 106.6915],
        [10.7705, 106.6970]
    ],
    color="blue",
    weight=5,
    tooltip="Tuyến giao hàng 2",
    popup="Tuyến phục vụ vùng nhu cầu trung bình và thấp"
).add_to(lop_tuyen)

lop_kho.add_to(ban_do)
lop_diem.add_to(ban_do)
lop_vung.add_to(ban_do)
lop_tuyen.add_to(ban_do)

Fullscreen().add_to(ban_do)
MiniMap().add_to(ban_do)
MeasureControl().add_to(ban_do)
folium.LayerControl(collapsed=False).add_to(ban_do)

display(ban_do)

print("NHẬN XÉT")
print("- Dashboard bản đồ tích hợp 4 lớp dữ liệu gồm kho trung tâm, điểm dịch vụ, vùng nhu cầu và tuyến giao hàng.")
print("- Người dùng có thể bật/tắt từng lớp để quan sát riêng từng loại thông tin hoặc xem tổng hợp.")
print("- Các vùng màu thể hiện mức nhu cầu khác nhau, hỗ trợ nhà quản trị nhận diện khu vực trọng điểm.")
print("- Các tuyến đường cho thấy hướng phục vụ và ưu tiên vận hành giữa kho với các điểm giao.")
print("- Dashboard này có thể hỗ trợ báo cáo quản trị và ra quyết định chiến lược trong logistics hoặc phân phối dịch vụ.")

#23.14
!pip install folium

import folium
from IPython.display import display

lo_trinh_xe = {
    "Xe 1": {
        "mau": "red",
        "trang_thai": ["Đang rảnh", "Đang đến đón khách", "Đã đón khách", "Đang giao khách", "Hoàn thành"],
        "duong_di": [
            (10.7769, 106.6953),
            (10.7780, 106.6965),
            (10.7795, 106.6980),
            (10.7810, 106.7000),
            (10.7825, 106.7015)
        ]
    },
    "Xe 2": {
        "mau": "blue",
        "trang_thai": ["Đang rảnh", "Đang đến điểm giao", "Đang giao hàng", "Sắp hoàn tất", "Hoàn thành"],
        "duong_di": [
            (10.7730, 106.6915),
            (10.7745, 106.6930),
            (10.7760, 106.6945),
            (10.7775, 106.6960),
            (10.7790, 106.6975)
        ]
    }
}

so_buoc = 5

for t in range(so_buoc):
    ban_do = folium.Map(location=[10.7769, 106.6953], zoom_start=14)

    for ten_xe, thong_tin in lo_trinh_xe.items():
        vi_tri_hien_tai = thong_tin["duong_di"][t]
        trang_thai_hien_tai = thong_tin["trang_thai"][t]
        mau = thong_tin["mau"]

        folium.Marker(
            vi_tri_hien_tai,
            popup=f"{ten_xe}<br>Thời gian: Bước {t+1}<br>Trạng thái: {trang_thai_hien_tai}",
            tooltip=f"{ten_xe} - {trang_thai_hien_tai}",
            icon=folium.Icon(color=mau)
        ).add_to(ban_do)

        folium.PolyLine(
            thong_tin["duong_di"][:t+1],
            color=mau,
            weight=4,
            tooltip=f"Lộ trình {ten_xe}"
        ).add_to(ban_do)

    print(f"===== BƯỚC THỜI GIAN {t+1} =====")
    display(ban_do)

    for ten_xe, thong_tin in lo_trinh_xe.items():
        print(f"{ten_xe}: {thong_tin['trang_thai'][t]}")
    print()

#23.15
!pip install folium scikit-learn

import folium
import numpy as np
from sklearn.cluster import KMeans
from IPython.display import display

khach_hang = np.array([
    [10.7765,106.6950],
    [10.7770,106.6960],
    [10.7780,106.6970],
    [10.7800,106.7000],
    [10.7810,106.7010],
    [10.7820,106.7020],

    [10.7720,106.6900],
    [10.7710,106.6890],
    [10.7700,106.6880],

    [10.7850,106.7050],
    [10.7860,106.7060],
    [10.7870,106.7070]
])

k = 3
model = KMeans(n_clusters=k, random_state=0)
labels = model.fit_predict(khach_hang)
centers = model.cluster_centers_

ban_do = folium.Map(location=[10.7769,106.6953], zoom_start=14)

colors = ["red","blue","green"]

for i in range(len(khach_hang)):
    folium.CircleMarker(
        location=khach_hang[i],
        radius=5,
        color=colors[labels[i]],
        fill=True,
        fill_opacity=0.7,
        popup=f"Khách - cụm {labels[i]}"
    ).add_to(ban_do)

for i, c in enumerate(centers):
    folium.Marker(
        location=c,
        popup=f"Kho đề xuất {i}",
        tooltip="Kho tối ưu",
        icon=folium.Icon(color="black", icon="home")
    ).add_to(ban_do)

display(ban_do)

print("Vị trí kho đề xuất:")
for i, c in enumerate(centers):
    print(f"Kho {i}: ({c[0]:.4f}, {c[1]:.4f})")

print()
print("NHẬN XÉT")
print("- Dữ liệu khách hàng được phân cụm bằng K-Means.")
print("- Tâm cụm là vị trí tối ưu để đặt kho trung chuyển.")
print("- Giúp giảm khoảng cách giao hàng và chi phí vận hành.")
print("- Ứng dụng thực tế trong logistics, gọi xe, giao hàng nhanh.")